### ISSUE TITLE
Unity Services

### ISSUE THREAD

**Issue by Loyale** [gofflab/gofflab_tasks#1]
Follow up and documentation of Unity Services pipette repair/recalibration

**Comment by chaichontat** [comment]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/34997334/212178150-f87c1472-a620-4554-ad84-7449b1b376fd.png">

**Comment by rlatanich** [comment]
Hi Folks-  To follow up on the pipette swallowed by Unity labs, I need either the serial number of the unit or a copy of the decontamination paperwork sent with the pipette. Would anyone know where to locate these items?

**Comment by chaichontat** [comment]
Unfortunately, I didn't write it down. Figured that the Order ID is enough.

**Comment by Loyale** [comment]
Rachel, is the issue that they can't find it or can't verify that it's ours?  The FedEx order number isn't enough to ID it?  Thanks for managing this.

**Comment by rlatanich** [comment]
Richard)  Well, a good lesson learned.  When sending out any piece of equipment a copy of the paperwork and a serial number should be documented.   We can make this a standard practice moving forward.
Loyal)  Apparently, they can't find it.  They've asked for a copy of our decontamination paperwork, which might help them.  Without some kind of identifier, we may be stuck here.

**Comment by chaichontat** [comment]
I did take a photo of it.
![image](https://user-images.githubusercontent.com/34997334/214397557-618f650a-75c2-497c-9d8a-8afb8a4b9e99.png)

**Comment by rlatanich** [comment]
That's perfect Richard!  Why didn't you share this earlier.  This is great!

**Comment by chaichontat** [comment]
Just popped up into my mind.

**Comment by chaichontat** [comment]
Received.
