### ISSUE TITLE
BSC Certification

### ISSUE THREAD

**Issue by chaichontat** [gofflab/gofflab_tasks#10]
Our biosafety cabinet is due for a certification by the end of this month (May).

**Comment by rlatanich** [comment]
Thank you so much for the heads up.  Can you please send me a picture of the sticker on the hood, along with the room number, and I'll get this scheduled today.

**Comment by chaichontat** [comment]
Room 534
![93512385-7EBB-4F6C-8B2C-FA8FB69DCFCE_1_102_o](https://github.com/gofflab/gofflab_tasks/assets/34997334/d4e53006-96b1-452e-98ba-87e6ccd10fcc)

**Comment by rlatanich** [comment]
Thank you Richard!

Warmly,
Rachel
____________________________________
Rachel Latanich
Research Manager| Department of Genetic Medicine
Operations Manager| Single Cell Training and Analysis Center (STAC)
Johns Hopkins University
MRB 423 | 733 N. Broadway, Baltimore, MD 21205
(O) 410-955-5765 | ***@***.***

________________________________
