### ISSUE TITLE
FACSAria Broken Connector

### ISSUE THREAD

**Issue by chaichontat** [gofflab/gofflab_tasks#4]
The FACSClean connector in the fluidics cart is broken.

![EC46F172-AFAB-4E3F-A2D5-8CFB001590A2_1_105_c](https://user-images.githubusercontent.com/34997334/212387767-802d313c-7b80-48b0-a640-c4307fc2b8ef.jpeg)

The issue of high CV has also been coming back.

**Comment by rlatanich** [comment]
Initiated replacement for FACS connector with BD.  Waiting of warranty verification from Green Lab.

**Comment by rlatanich** [comment]
Hi Richard-  BD has responded with additional questions.  If you have time, could you send more pictures:  If you don't have time, that's okay.  I'll be back next week.

Here is their response:

_My_ question: Where the  broken connector goes into the wetcart is that connector (Female side) Ok? More images
of the filter that the broken connector is attached to as well as the  end that the connector fits into would be very helpful._

**Comment by chaichontat** [comment]
This is a photo from inside the fluidics cart for your reference. BD wouldn't like us looking inside.

![41F56D24-49C4-4017-8546-F3916F8E334D_1_105_c](https://user-images.githubusercontent.com/34997334/213268844-2e5247fa-ba64-4b19-87f0-f1f4fc3eea79.jpeg)

Basically, the connector in the cart snapped in half which detached it from the opening of the cart. The other half of the connector is still connected to the filter visible in the first pic.

**Comment by chaichontat** [comment]
This is a photo from inside the fluidics cart for your reference. BD wouldn't like us looking inside.

![41F56D24-49C4-4017-8546-F3916F8E334D_1_105_c](https://user-images.githubusercontent.com/34997334/213268844-2e5247fa-ba64-4b19-87f0-f1f4fc3eea79.jpeg)

Basically, the connector in the cart snapped in half which detached it from the opening of the cart. The other half of the connector is still connected to the filter visible in the first pic.

**Comment by chaichontat** [comment]
This is a photo from inside the fluidics cart for your reference. BD wouldn't like us looking inside.

![41F56D24-49C4-4017-8546-F3916F8E334D_1_105_c](https://user-images.githubusercontent.com/34997334/213268844-2e5247fa-ba64-4b19-87f0-f1f4fc3eea79.jpeg)

Basically, the connector in the cart snapped in half which detached it from the opening of the cart. The other half of the connector is still connected to the filter visible in the first pic.

**Comment by chaichontat** [comment]
Resolved with a service visit on 8th Feb 23.
