### ISSUE TITLE
Xplorer Replacement

### ISSUE THREAD

**Issue by chaichontat** [gofflab/gofflab_tasks#5]
We will be sending back the: XPLORER SINGLE-CHANNEL*50-1000UL*BLUE this week under terms of its warranty.  Once USA Scientific reviews the instrument, a replacement will be sent.  I'll be by to grab on Friday.

**Comment by rlatanich** [comment]
Tentative ship date for xplorer: 02/06/2023

**Comment by chaichontat** [comment]
Replacement received.
